### ISSUE TITLE
Project handover

### ISSUE THREAD

**Issue by Lizzy-j** [fac19/criminal-appeals-fund#16]
- [x] Set up an account for Kwame to view user accounts and applications

- [x] Create UI overlay for Kwame - data visualisation? Easy yes/no on applications?

- [x] Write how-to guide for Airtable

- [x] Write an accessible overview of how the whole project fits together

**Comment by Lizzy-j** [comment]
Make sure to inform Kwame about Airtable subscription plan

**Comment by jackherizsmith** [comment]
> Make sure to inform Kwame about Airtable subscription plan

@Lizzy-j could you expand on this? How will the service change?
