### ISSUE TITLE
Sign up form

### ISSUE THREAD

**Issue by CampbellDocherty** [fac19/criminal-appeals-fund#20]
- [x] Page 1 - First name, last name, email, bar number

- [x] Page 2 - Picture upload

- [x] Page 3 - Password

- [x] validation

**Comment by itsina96** [comment]
<img width="861" alt="Screenshot 2020-06-05 at 10 38 58" src="https://user-images.githubusercontent.com/53597131/83861833-02ba3480-a719-11ea-9f81-12dffa007a3e.png">

**Comment by itsina96** [comment]
<img width="273" alt="Screenshot 2020-06-05 at 10 41 22" src="https://user-images.githubusercontent.com/53597131/83861904-1cf41280-a719-11ea-8910-c99963d6d74e.png">
