### ISSUE TITLE
Application form

### ISSUE THREAD

**Issue by CampbellDocherty** [fac19/criminal-appeals-fund#21]
- [x]  1 - Funding criteria

- [x]  2 - Clusters

- [x]  3 - Document uploads

**Comment by itsina96** [comment]
<img width="861" alt="Screenshot 2020-06-05 at 10 38 58" src="https://user-images.githubusercontent.com/53597131/83861991-3c8b3b00-a719-11ea-92a3-36cd687ab69e.png">
