### ISSUE TITLE
coverage files??

### ISSUE THREAD

**Issue by jackherizsmith** [fac19/criminal-appeals-fund#46]
What are we missing in our scripts to generate coverage files for codecov?

**Comment by jamesj-0** [comment]
In our project we didn't have a code cov yml file. We did however include the code cov generate report in out travis yml.

Just attached it here 👇
`language: node_js
node_js:
  - lts/*
  
cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run test:report && codecov

after-script:
  - bash <(curl -s https://codecov.io/bash)
`
I looked at your README badge and it seems to be the same code as ours -> 
[![codecov](https://codecov.io/gh/fac19/Zaatari-Radio/branch/master/graph/badge.svg)](https://codecov.io/gh/fac19/Zaatari-Radio)

Let me know if that works! Im still unsure how to exclude files from the report, Gio wrote some great docs on how to set it all up [here](https://www.notion.so/Codecov-with-Jest-React-e5ba9c92a98d43b9b25bd9c1022403dc) 😁 

^this is with jest. Vats is trying work out how to integrate it with Cyprus at the moment

**Comment by jamesj-0** [comment]
^ tried to put that code in tags but its come out a bit rubbish!

**Comment by Ivo-Evans** [comment]
So you are generating the files - when you run `npm run test` it creates a coverage file. You need to send these files to codecov. The easiest way to do that is to get travis to do it for you by editing your .travis.yml, as above. The most important lines there are 

```
install:
    npm ci
script:
    npm run test:report
after-script:
    bash <(curl -s https://codecov.io/bash)
```

You don't actually need && codecov or codecov as a dependency
