### ISSUE TITLE
UX feedback (with some error handling feedback)

### ISSUE THREAD

**Issue by VatsKan** [fac19/criminal-appeals-fund#48]
I used your website on netlify, and these were some tips from the user experience i had. I am sure you are already aware of most of the points made here. Overall looks really cool and everything seems to be working and generally intuitive to use. 

### Home page
- [x] Little strange that home page scrolls you down to half way on first visit, and I have to scroll up to see what's at the top of the page (on netlify deployment). If the steps are the first thing the user needs to see, perhaps consider putting it at the top of the page (but I suppose this is a style choice).

### Sign Up
- [x] error mesage on signing up is "Please fill in this field" although I have filled in all the fields (perhaps the email incorrectly without the @ sign). More specific error messages would be nice.
- [x] not sure what the upload file is on Sign up. only after i try to click sign up i see an error message saying please provide ID, otherwise i wouldn't know what file to upload.
- [x] no feedback once you have uploaded file to know that the file has actually been uploaded.

### Profile page
- [x] instead of greying out the 'back' button perhaps remove it entirely on page 1... as if the user tries to click it they may think it is not working. 
- [x] there are a few options 'apply for funding', 'generate invoice' 'next'... but im not sure which is the right button to click (what the next step ideally is in the user journey) as they all seem equally important and all being seen at the same time. (the 'generate invoice' at step 3 ... also not sure why this is at step 3 and not final step)
- [x] after finishing clicking next, next, next, next, it then says "funded", but not sure why as I haven't yet clicked the 'apply for funding' button. 

### Apply page
- [x] greyed out back button doesn't look great and takes up space on the page (better to remove it if it isn't going to do anything). You can use ```visibility: hidden``` to allocate space for it but not display it on the page. (```display: none``` does not allocate space for it but removes it from the DOM entirely i believe). 
- [x] not sure what 'application document' means when you try to upload file.. only see it as an error message, but not sure what file you want me to upload before hand.
- [x] no feedback once you have uploaded file to know that the file has actually been uploaded.

### Login
- [x] you are probably aware that i can login with any credentials (no checking at the moment).

**Comment by jackherizsmith** [comment]
Thanks you @VatsKan very thorough
